extends:
- eslint:recommended
- plugin:react/recommended
- plugin:jest/recommended
plugins:
- react
- jest
env:
  jest/globals: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 2017
  sourceType: module
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
globals:
  process: true
